
services:
  storage-service:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://172.20.10.5:27017/chunkDatabase
    volumes:
      - /data/chunks_storage:/data/chunks_storage

volumes:
  chunks_storage:
